### ISSUE TITLE
uninitialized constant MiniTest (NameError)

### ISSUE THREAD

**Issue by go2null** [mfpiccolo/minitest-vcr#29]
Saw this gem listed as a [Known Extension](http://docs.seattlerb.org/minitest/#label-Known+Extensions-3A), decided to try it and got the following error
```
C:/Users/USER/opt/Ruby31-x64/lib/ruby/gems/3.1.0/gems/minispec-metadata-2.0.0/lib/core_extensions.rb:3:in `<top (required)>': uninitialized constant MiniTest (NameError)

if MiniTest.const_defined?(:Unit)
   ^^^^^^^^
Did you mean?  Minitest
        from C:/Users/USER/opt/Ruby31-x64/lib/ruby/gems/3.1.0/gems/minispec-metadata-2.0.0/lib/minispec-metadata.rb:2:in `require_relative'
        from C:/Users/USER/opt/Ruby31-x64/lib/ruby/gems/3.1.0/gems/minispec-metadata-2.0.0/lib/minispec-metadata.rb:2:in `<top (required)>'
        from C:/Users/USER/opt/Ruby31-x64/lib/ruby/gems/3.1.0/gems/minitest-vcr-1.4.0/lib/minitest-vcr/spec.rb:2:in `require'
        from C:/Users/USER/opt/Ruby31-x64/lib/ruby/gems/3.1.0/gems/minitest-vcr-1.4.0/lib/minitest-vcr/spec.rb:2:in `<top (required)>'
        from C:/Users/USER/opt/Ruby31-x64/lib/ruby/gems/3.1.0/gems/minitest-vcr-1.4.0/lib/minitest-vcr.rb:2:in `require'
        from C:/Users/USER/opt/Ruby31-x64/lib/ruby/gems/3.1.0/gems/minitest-vcr-1.4.0/lib/minitest-vcr.rb:2:in `<top (required)>'
        from C:/Users/USER/src/gitlab-report/spec/spec_helper.rb:13:in `require'
        from C:/Users/USER/src/gitlab-report/spec/spec_helper.rb:13:in `<top (required)>'
        from C:/Users/USER/src/gitlab-report/spec/gitlab_report/csv_report_spec.rb:3:in `require_relative'
        from C:/Users/USER/src/gitlab-report/spec/gitlab_report/csv_report_spec.rb:3:in `<top (required)>'
        from C:/Users/USER/opt/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:21:in `require'
        from C:/Users/USER/opt/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:21:in `block in <main>'
        from C:/Users/USER/opt/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:6:in `select'
        from C:/Users/USER/opt/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:6:in `<main>'
rake aborted!
```

**Comment by go2null** [comment]
Excerpt from `Gemfile.lock`
```ruby
    minispec-metadata (2.0.0)
      minitest
    minitest (5.20.0)
    minitest-vcr (1.4.0)
      minispec-metadata (~> 2.0)
      minitest (>= 4.7.5)
      vcr (>= 2.9)
    vcr (6.2.0)
```
